### ISSUE TITLE
How is the stack related to this.pubnub.init(this)

### ISSUE THREAD

**Issue by vikramkh** [pubnub/react#42]
Hey guys, I'm trying to use pubnub, but having some problems of it not being accessible across different components. The way my app is set up is (using react navigation 4.x) I have
An App container,
A switch navigator between Auth stack, and a bottom tab navigator. I don't want to preemptively create a pubnub object so I don't pass it to the app container (and I also don't have the users credentials then to set the UUID). Instead, I initialize it in one of the tabs (components) in the bottom tab navigator, and then store it in redux. However, it does not work in other components, unless I run init(this) again in that components state. Is this fine to do?

**Comment by vikramkh** [comment]
Also, I feel like the solution is to use v2.0 but it's for a production app, so can I use the beta version in a production app? Is there any timeline for v2.0?

**Comment by are** [comment]
Hi @vikramkh, just to answer the second question - yes, v2.0 is probably going to solve some of those problems, and we are releasing it this week! You can go ahead and use the v2.0 beta (or even RC version since this one is going to be the official release). You can install the RC as such: `npm install pubnub-react@rc`.
